- hosts: localhost
  connection: local
  vars:
    resource_group_webapp: RG-EU2-FACR20M-PRD
    #resource_group: myResourceGroup
    webapp_name: pseproduction
    #plan_name: myAppServicePlan
    #location: eastus
    #traffic_manager_profile_name: myTrafficManagerProfile
    #traffic_manager_endpoint_name: myTrafficManagerEndpoint

  tasks:
  - name: Get web app facts
    azure_rm_webapp_facts:
      resource_group: "{{ resource_group_webapp }}"
      name: "{{ webapp_name }}"
    #register: webapp